services:
  mongodb:
    image: jotaantunes03/mongo:6.0
    container_name: goals_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - goals-network

  frontend:
    image: jotaantunes03/goals-frontend
    depends_on:
      - backend
    ports:
      - "4000:3000"
    networks:
      - goals-network

  backend:
    image: jotaantunes03/goals-backend
    depends_on:
      - mongodb
    ports:
      - "5001:80"
    networks:
      - goals-network
    environment:
      - MONGO_HOST=mongodb
      - MONGO_USER=admin
      - MONGO_PASSWORD=admin
      - MONGO_DB=course-goals
      - MONGO_URI=mongodb://mongodb:27017/course-goals
    volumes:
      - ./backend/logs:/app/logs
volumes:
  mongo_data:

networks:
  goals-network:
    driver: bridge